# Generated by Django 5.2 on 2025-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
