# Generated by Django 5.2 on 2025-04-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_productvariant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
