# Generated by Django 5.2 on 2025-04-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_contactmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmessage",
            name="created_at",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
    ]
