# Generated by Django 5.2 on 2025-05-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orderitem_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
